[build]
  command = "pnpm install && mkdir -p public && cp -r models thumbnails styles public/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/categories"
  status = 200

[[redirects]]
  from = "/api/models/all"
  to = "/.netlify/functions/models"
  status = 200

# Catch-all redirect for other /api endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "pnpm start"
  port = 3000
  publish = "/" 