[build]
  command = "pnpm install && mkdir -p public && cp index.html public/ && [ -d styles ] && cp -r styles public/ || true && [ -d models ] && cp -r models public/ || true && [ -d thumbnails ] && cp -r thumbnails public/ || true"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["models/**", "thumbnails/**"]

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "pnpm start"
  port = 3000
  publish = "/" 